-- Database Setup for Subscription Renewal Management

CREATE TABLE RENEWAL_TB (
    RENEWALID VARCHAR2(12) PRIMARY KEY,
    SUBSCRIBERNAME VARCHAR2(50) NOT NULL,
    SUBSCRIPTIONID VARCHAR2(20) NOT NULL,
    RENEWALDATE DATE NOT NULL,
    AMOUNT NUMBER NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    REMARKS VARCHAR2(100)
);

CREATE SEQUENCE RENEWAL_SEQ
START WITH 10
INCREMENT BY 1
MAXVALUE 99;

SELECT * FROM SYSTEM.RENEWAL_TB;
